FROM ubuntu

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y openssh-server wget git nano curl iputils-ping

RUN apt install -y build-essential
RUN apt-get install -y openmpi-bin openmpi-doc libopenmpi-dev

RUN useradd -m -s /bin/bash ubuntu \
    && echo 'ubuntu:ubuntu' | chpasswd

# Allow SSH access for the non-root user
RUN mkdir -p /home/ubuntu/.ssh \
    && chmod 700 /home/ubuntu/.ssh \
    && touch /home/ubuntu/.ssh/authorized_keys \
    && chmod 600 /home/ubuntu/.ssh/authorized_keys \
    && chown -R ubuntu:ubuntu /home/ubuntu/.ssh

RUN mkdir /var/run/sshd \
    && mkdir /var/run/sshd/empty

RUN apt-get install sudo
RUN usermod -aG sudo ubuntu

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]